# Generated by Django 5.1.3 on 2024-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wish_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
